services:
  - type: web
    name: jpg-smartwash
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn jgp_smartwash.wsgi:application